# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: j:/vivado/project/ti/jnu2023h/jnu2023h.srcs/sources_1/ip/cordic_0/cordic_0.xci
# IP: The module: 'cordic_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: j:/vivado/project/ti/jnu2023h/jnu2023h.gen/sources_1/ip/cordic_0/cordic_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cordic_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: j:/vivado/project/ti/jnu2023h/jnu2023h.srcs/sources_1/ip/cordic_0/cordic_0.xci
# IP: The module: 'cordic_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: j:/vivado/project/ti/jnu2023h/jnu2023h.gen/sources_1/ip/cordic_0/cordic_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cordic_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
