create_clock -period 20.000 -name sys_clk [get_ports sys_clk]

set_property -dict {PACKAGE_PIN R4 IOSTANDARD LVCMOS33} [get_ports sys_clk]
set_property -dict {PACKAGE_PIN U2 IOSTANDARD LVCMOS33} [get_ports rst_n]

set_property -dict {PACKAGE_PIN T1 IOSTANDARD LVCMOS33} [get_ports {key[0]}]
set_property -dict {PACKAGE_PIN U1 IOSTANDARD LVCMOS33} [get_ports {key[1]}]
set_property -dict {PACKAGE_PIN W2 IOSTANDARD LVCMOS33} [get_ports {key[2]}]
set_property -dict {PACKAGE_PIN T3 IOSTANDARD LVCMOS33} [get_ports {key[3]}]

set_property -dict {PACKAGE_PIN G18 IOSTANDARD LVCMOS33} [get_ports {seg_sel[5]}]
set_property -dict {PACKAGE_PIN H18 IOSTANDARD LVCMOS33} [get_ports {seg_sel[4]}]
set_property -dict {PACKAGE_PIN G17 IOSTANDARD LVCMOS33} [get_ports {seg_sel[3]}]
set_property -dict {PACKAGE_PIN H13 IOSTANDARD LVCMOS33} [get_ports {seg_sel[2]}]
set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS33} [get_ports {seg_sel[1]}]
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports {seg_sel[0]}]

set_property -dict {PACKAGE_PIN H15 IOSTANDARD LVCMOS33} [get_ports {seg_led[0]}]
set_property -dict {PACKAGE_PIN G16 IOSTANDARD LVCMOS33} [get_ports {seg_led[1]}]
set_property -dict {PACKAGE_PIN L13 IOSTANDARD LVCMOS33} [get_ports {seg_led[2]}]
set_property -dict {PACKAGE_PIN G15 IOSTANDARD LVCMOS33} [get_ports {seg_led[3]}]
set_property -dict {PACKAGE_PIN K13 IOSTANDARD LVCMOS33} [get_ports {seg_led[4]}]
set_property -dict {PACKAGE_PIN G13 IOSTANDARD LVCMOS33} [get_ports {seg_led[5]}]
set_property -dict {PACKAGE_PIN H14 IOSTANDARD LVCMOS33} [get_ports {seg_led[6]}]
set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33} [get_ports {seg_led[7]}]

set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN D17} [get_ports {dac1_data[7]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN E17} [get_ports {dac1_data[6]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN F18} [get_ports {dac1_data[5]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN F21} [get_ports {dac1_data[4]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN M18} [get_ports {dac1_data[3]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN L18} [get_ports {dac1_data[2]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN H20} [get_ports {dac1_data[1]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN G20} [get_ports {dac1_data[0]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN N22} [get_ports dac1_clk]

set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN N13} [get_ports {dac2_data[7]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN N14} [get_ports {dac2_data[6]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN P14} [get_ports {dac2_data[5]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN R14} [get_ports {dac2_data[4]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN P15} [get_ports {dac2_data[3]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN R16} [get_ports {dac2_data[2]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN P17} [get_ports {dac2_data[1]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN N17} [get_ports {dac2_data[0]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V9} [get_ports dac2_clk]

set_property IOSTANDARD LVCMOS33 [get_ports {ad_data_1[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data_1[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data_1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data_1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data_1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data_1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data_1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data_1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data_1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data_1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data_2[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data_2[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data_2[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data_2[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data_2[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data_2[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data_2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data_2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data_2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data_2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports ad_clk_1]
set_property IOSTANDARD LVCMOS33 [get_ports ad_clk_2]
set_property PACKAGE_PIN E17 [get_ports ad_clk_1]
set_property PACKAGE_PIN T20 [get_ports ad_clk_2]
set_property PACKAGE_PIN E19 [get_ports {ad_data_1[0]}]
set_property PACKAGE_PIN D19 [get_ports {ad_data_1[1]}]
set_property PACKAGE_PIN G22 [get_ports {ad_data_1[2]}]
set_property PACKAGE_PIN G21 [get_ports {ad_data_1[3]}]
set_property PACKAGE_PIN J22 [get_ports {ad_data_1[4]}]
set_property PACKAGE_PIN H22 [get_ports {ad_data_1[5]}]
set_property PACKAGE_PIN K22 [get_ports {ad_data_1[6]}]
set_property PACKAGE_PIN K21 [get_ports {ad_data_1[7]}]
set_property PACKAGE_PIN M21 [get_ports {ad_data_1[8]}]
set_property PACKAGE_PIN L21 [get_ports {ad_data_1[9]}]
set_property PACKAGE_PIN F21 [get_ports {ad_data_2[0]}]
set_property PACKAGE_PIN F18 [get_ports {ad_data_2[1]}]
set_property PACKAGE_PIN L18 [get_ports {ad_data_2[2]}]
set_property PACKAGE_PIN M18 [get_ports {ad_data_2[3]}]
set_property PACKAGE_PIN G20 [get_ports {ad_data_2[4]}]
set_property PACKAGE_PIN H20 [get_ports {ad_data_2[5]}]
set_property PACKAGE_PIN J21 [get_ports {ad_data_2[6]}]
set_property PACKAGE_PIN J20 [get_ports {ad_data_2[7]}]
set_property PACKAGE_PIN M20 [get_ports {ad_data_2[8]}]
set_property PACKAGE_PIN N20 [get_ports {ad_data_2[9]}]
set_property PACKAGE_PIN M22 [get_ports ad_oe_1]
set_property PACKAGE_PIN N18 [get_ports ad_oe_2]
set_property PACKAGE_PIN N22 [get_ports ad_otr_1]
set_property PACKAGE_PIN N19 [get_ports ad_otr_2]
set_property IOSTANDARD LVCMOS33 [get_ports ad_oe_1]
set_property IOSTANDARD LVCMOS33 [get_ports ad_oe_2]
set_property IOSTANDARD LVCMOS33 [get_ports ad_otr_1]
set_property IOSTANDARD LVCMOS33 [get_ports ad_otr_2]
