# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/sb/Desktop/git/jnu2023h/jnu2023h.srcs/sources_1/ip/ram_4096x16/ram_4096x16.xci
# IP: The module: 'ram_4096x16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/sb/Desktop/git/jnu2023h/jnu2023h.gen/sources_1/ip/ram_4096x16/ram_4096x16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_4096x16'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/sb/Desktop/git/jnu2023h/jnu2023h.srcs/sources_1/ip/ram_4096x16/ram_4096x16.xci
# IP: The module: 'ram_4096x16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/sb/Desktop/git/jnu2023h/jnu2023h.gen/sources_1/ip/ram_4096x16/ram_4096x16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_4096x16'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
