create_clock -period 20.000 -name sys_clk [get_ports sys_clk]

set_property -dict {PACKAGE_PIN R4 IOSTANDARD LVCMOS33} [get_ports sys_clk]
set_property -dict {PACKAGE_PIN U2 IOSTANDARD LVCMOS33} [get_ports rst_n]

set_property -dict {PACKAGE_PIN T1 IOSTANDARD LVCMOS33} [get_ports {key[0]}]
set_property -dict {PACKAGE_PIN U1 IOSTANDARD LVCMOS33} [get_ports {key[1]}]
set_property -dict {PACKAGE_PIN W2 IOSTANDARD LVCMOS33} [get_ports {key[2]}]
set_property -dict {PACKAGE_PIN T3 IOSTANDARD LVCMOS33} [get_ports {key[3]}]

#AD接口
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN K22} [get_ports {adc1_data[7]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN K21} [get_ports {adc1_data[6]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN J22} [get_ports {adc1_data[5]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN H22} [get_ports {adc1_data[4]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN G22} [get_ports {adc1_data[3]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN G21} [get_ports {adc1_data[2]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN E19} [get_ports {adc1_data[1]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN D19} [get_ports {adc1_data[0]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN M21} [get_ports ad1_clk]

set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN U7} [get_ports {adc2_data[7]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN AB7} [get_ports {adc2_data[6]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V7} [get_ports {adc2_data[5]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN AB6} [get_ports {adc2_data[4]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN AB8} [get_ports {adc2_data[3]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN AA8} [get_ports {adc2_data[2]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN Y8} [get_ports {adc2_data[1]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN Y7} [get_ports {adc2_data[0]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN Y9} [get_ports adc2_clk]

#DA接口
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN D17} [get_ports {dac1_data[7]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN E17} [get_ports {dac1_data[6]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN F18} [get_ports {dac1_data[5]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN F21} [get_ports {dac1_data[4]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN M18} [get_ports {dac1_data[3]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN L18} [get_ports {dac1_data[2]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN H20} [get_ports {dac1_data[1]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN G20} [get_ports {dac1_data[0]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN N22} [get_ports dac1_clk]

set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN N13} [get_ports {dac2_data[7]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN N14} [get_ports {dac2_data[6]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN P14} [get_ports {dac2_data[5]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN R14} [get_ports {dac2_data[4]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN P15} [get_ports {dac2_data[3]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN R16} [get_ports {dac2_data[2]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN P17} [get_ports {dac2_data[1]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN N17} [get_ports {dac2_data[0]}] 
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V9} [get_ports dac2_clk]
