
#时序约束

create_clock -period 20.000 -name sys_clk [get_ports sys_clk]
set_property -dict {PACKAGE_PIN R4 IOSTANDARD LVCMOS33} [get_ports sys_clk]
set_property -dict {PACKAGE_PIN U2 IOSTANDARD LVCMOS33} [get_ports sys_rst_n]


set_property IOSTANDARD LVCMOS33 [get_ports {da_data_1[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data_1[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data_1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data_1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data_1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data_1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data_1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data_1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data_1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data_1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data_2[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data_2[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data_2[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data_2[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data_2[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data_2[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data_2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data_2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data_2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data_2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports da_clk_1]
set_property IOSTANDARD LVCMOS33 [get_ports da_clk_2]
set_property PACKAGE_PIN Y7 [get_ports da_clk_1]
set_property PACKAGE_PIN Y8 [get_ports {da_data_1[0]}]
set_property PACKAGE_PIN AA8 [get_ports {da_data_1[1]}]
set_property PACKAGE_PIN AB8 [get_ports {da_data_1[2]}]
set_property PACKAGE_PIN AB6 [get_ports {da_data_1[3]}]
set_property PACKAGE_PIN V7 [get_ports {da_data_1[4]}]
set_property PACKAGE_PIN AB7 [get_ports {da_data_1[5]}]
set_property PACKAGE_PIN U7 [get_ports {da_data_1[6]}]
set_property PACKAGE_PIN V8 [get_ports {da_data_1[7]}]
set_property PACKAGE_PIN Y9 [get_ports {da_data_1[8]}]
set_property PACKAGE_PIN W9 [get_ports {da_data_1[9]}]
set_property PACKAGE_PIN P15 [get_ports {da_data_2[0]}]
set_property PACKAGE_PIN R14 [get_ports da_clk_2]
set_property PACKAGE_PIN R16 [get_ports {da_data_2[1]}]
set_property PACKAGE_PIN P17 [get_ports {da_data_2[2]}]
set_property PACKAGE_PIN N17 [get_ports {da_data_2[3]}]
set_property PACKAGE_PIN R18 [get_ports {da_data_2[4]}]
set_property PACKAGE_PIN V20 [get_ports {da_data_2[5]}]
set_property PACKAGE_PIN T18 [get_ports {da_data_2[6]}]
set_property PACKAGE_PIN V19 [get_ports {da_data_2[7]}]
set_property PACKAGE_PIN U17 [get_ports {da_data_2[8]}]
set_property PACKAGE_PIN U18 [get_ports {da_data_2[9]}]
