# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/FPGA/DDS/dds.srcs/sources_1/ip/rom_200x8b/rom_200x8b.xci
# IP: The module: 'rom_200x8b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA/DDS/dds.gen/sources_1/ip/rom_200x8b/rom_200x8b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_200x8b'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/FPGA/DDS/dds.srcs/sources_1/ip/rom_200x8b/rom_200x8b.xci
# IP: The module: 'rom_200x8b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA/DDS/dds.gen/sources_1/ip/rom_200x8b/rom_200x8b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_200x8b'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
